-- Messages of one turn are inserted in a single batch, so they share an identical created_at.
-- Ordering history by created_at then returns them in a nondeterministic order, which can place a
-- tool_use before something other than its tool_result → Anthropic 400 ("tool_use ids were found
-- without tool_result blocks immediately after"). A monotonic identity column gives a stable,
-- insertion-order sort. getHistory() orders by seq.
alter table egs_messages add column if not exists seq bigint generated by default as identity;

create index if not exists egs_messages_seq_idx on egs_messages(project_id, seq);
